version: "2"
plugins:
    cppcheck:
        enabled: true
        config:
            check: all
            language: c++
            stds:
                - c++11
            includes:
                - src/
                - src/include/cpp-crypto
exclude_patterns:
  - "src/lib/"
  - "extern/"
  - "test/"
