name: CodeClimate Coverage

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  codeclimate:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set compiler to clang++
        run: COMPILER=clang++
      - name: Install Dependencies
        run: brew install cmake lcov
      - name: Make scripts executable
        run: sudo chmod +x ./.github/workflows/test/clang_tidy.sh
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Build & Run Coverage Tests
        run: |
          ./cc-test-reporter before-build
          cmake -DCMAKE_BUILD_TYPE=Coverage -DUNIT_TEST=ON .
          cmake --build .
          ./test/ark_cpp_crypto_tests
          lcov --directory . --include "*/src/*" --include "*/test/*" --exclude "*/src/lib/*" --exclude "*/extern/*" --capture --output-file coverage.info --ignore-errors gcov
          ./cc-test-reporter format-coverage --input-type lcov coverage.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
